// The 11 Yelema experts. Each key is also the Hermes profile name on the workspace instance.
// Copy comes from the yelema-front-v2 mockup (recrue-<key>.html, recruter.html, app.js).

export type ExpertKey =
  | "djeneba"
  | "fatima"
  | "koffi"
  | "kouassi"
  | "awa"
  | "adjoua"
  | "mamadou"
  | "salif"
  | "alioune"
  | "nadia"
  | "ibrahim";

export interface Expert {
  key: ExpertKey;
  name: string; // "Fatima", "Djénéba"
  pronoun: "elle" | "il";
  role: string; // gallery/fiche role line, e.g. "Marketing & Contenu"
  title: string; // short home-card title, e.g. "Marketing et contenu", "Chief of Staff"
  category: string; // the recruter filter chip label this expert belongs to
  tagline: string; // one line, e.g. "Elle fait vivre votre marque, chaque semaine."
  pitch: string; // the Fiche de poste intro paragraph
  inAction: string; // the "En action" paragraph
  skills: { title: string; description: string }[];
  daily: string[];
  approvals: string[];
  routines: { title: string; cadence: string }[];
  deliverables: { title: string; description: string }[];
  needs: string[];
  tools: string[];
  terrain: string;
  suggestions: string[]; // short French prompts a user can send this expert in chat
}

export const EXPERTS: Expert[] = [
  {
    key: "djeneba",
    name: "Djénéba",
    pronoun: "elle",
    role: "Chief of Staff & Direction",
    title: "Chief of Staff",
    category: "Direction",
    tagline: "Elle orchestre l’équipe IA, aligne les priorités et libère votre agenda.",
    pitch: "Bras droit du dirigeant : elle prépare ses réunions, filtre ses sollicitations, tient le relevé des décisions et suit les engagements pris.",
    inAction: "Le dirigeant enchaîne cinq rendez-vous. Djénéba prépare un brief par réunion avec l'historique et l'objectif, écarte trois sollicitations qui pouvaient attendre, consigne les décisions prises et relance deux engagements de la semaine précédente restés sans suite.",
    skills: [
      { title: "Brief de rendez-vous", description: "Prépare chaque réunion avec contexte, historique et objectif de la rencontre." },
      { title: "Ordre du jour & note de cadrage", description: "Rédige l'ordre du jour et la note de cadrage avant chaque réunion stratégique." },
      { title: "Relevé de décisions", description: "Consigne les décisions prises après chaque réunion et les distribue aux parties concernées." },
      { title: "Suivi des engagements", description: "Tient le tableau des engagements pris et relance automatiquement les retardataires." },
      { title: "Filtre & priorisation", description: "Trie les sollicitations entrantes et ne remonte que ce qui mérite votre attention directe." },
      { title: "Point hebdomadaire", description: "Produit chaque semaine un point synthétique sur ce qui est en attente ou en retard." },
    ],
    daily: [
      "Prépare vos rendez-vous",
      "Filtre et priorise ce qui arrive",
      "Prend le relevé des décisions",
      "Relance les engagements non tenus",
    ],
    approvals: [
      "Envoi d'un message en votre nom",
      "Acceptation ou refus d'un rendez-vous",
      "Diffusion d'un relevé de décisions",
      "Engagement pris auprès d'un tiers",
    ],
    routines: [
      { title: "Prépare la journée du dirigeant", cadence: "Chaque jour ouvré" },
      { title: "Fait la veille du secteur de l'entreprise", cadence: "Chaque semaine" },
      { title: "Trie la boîte mail de direction et prépare les réponses", cadence: "Chaque jour ouvré" },
      { title: "Fait le point sur les engagements pris et prépare les relances", cadence: "Deux fois par semaine" },
      { title: "Refait le tri de la boîte mail de direction à la mi-journée", cadence: "Chaque jour ouvré" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "Brief de rendez-vous", description: "Qui vous rencontrez, l'historique des échanges, l'objectif et les trois points à obtenir." },
      { title: "Ordre du jour et note de cadrage", description: "Les sujets, le temps accordé à chacun et la décision attendue." },
      { title: "Relevé de décisions", description: "Ce qui a été décidé, par qui, pour quand, envoyé le jour même." },
      { title: "Tableau des engagements", description: "Chaque promesse faite en réunion, son responsable et son échéance, relancée à temps." },
      { title: "Tri de votre boîte", description: "Les messages qui demandent votre décision, ceux qu'elle traite, ceux qui attendent." },
      { title: "Point hebdomadaire", description: "Ce qui a avancé, ce qui bloque et ce qu'il vous revient de trancher." },
      { title: "Radar de la semaine", description: "Les échéances, rendez-vous et sujets à préparer dans les sept jours qui viennent." },
      { title: "Pack de comité de direction", description: "L'ordre du jour, les documents à lire et la synthèse de chaque dossier." },
      { title: "Préparation de déplacement", description: "Le programme, les rendez-vous, les billets, l'hôtel et les contacts sur place." },
    ],
    needs: [
      "Agenda du dirigeant",
      "Historique emails & messages",
      "Comptes rendus de réunions",
      "Liste des interlocuteurs clés",
      "Priorités du trimestre",
    ],
    tools: [
      "Agenda",
      "Gmail",
      "WhatsApp",
      "Notion",
      "Google Drive",
      "Slack",
    ],
    terrain: "Elle connaît le terrain administratif d'un dirigeant : le calendrier officiel ivoirien, les usages avec les guichets, et les circuits par lesquels passent les démarches d'une entreprise. Elle sait quelles pièces un guichet réclame vraiment, combien de temps une démarche prend en pratique, et à quel moment relancer pour que le dossier avance.",
    suggestions: [
      "Prépare mon point du jour",
      "Rédige la note du comité de direction",
      "Prépare le brief de mon rendez-vous",
      "Résume la semaine pour la direction",
    ],
  },
  {
    key: "fatima",
    name: "Fatima",
    pronoun: "elle",
    role: "Marketing & Contenu",
    title: "Marketing et contenu",
    category: "Marketing et design",
    tagline: "Elle fait vivre votre marque, chaque semaine.",
    pitch: "La présence de marque complète : stratégie, production et programmation des contenus, animation des réseaux et relation presse, dans votre voix.",
    inAction: "Pour le lancement d'une offre, Fatima propose un plan de 6 posts, rédige les textes, prépare les visuels, programme la semaine et livre une newsletter prête à valider. Le fondateur relit et publie en un clic.",
    skills: [
      { title: "Stratégie de marque", description: "Positionnement, voix de marque et message : le socle de votre communication." },
      { title: "Calendrier éditorial", description: "Planifie et produit les posts multi-réseaux (attirer / convertir / fidéliser)." },
      { title: "Visuels de marque (Canva)", description: "Génère posts, carrousels et stories brandés, prêts à publier." },
      { title: "Programmation multi-canaux", description: "Programme les publications au bon moment, au format natif de chaque plateforme." },
      { title: "Community management", description: "Trie et répond aux commentaires et messages privés sur les réseaux." },
      { title: "Veille des tendances", description: "Suit chaque semaine les tendances des réseaux par canal et par pays." },
      { title: "SEO", description: "Mots-clés, briefs et suivi de positions pour être trouvé sur Google." },
      { title: "Publicité payante", description: "Décide où, combien et comment investir avant la première campagne." },
      { title: "Relations presse", description: "Sourcing de médias, communiqués et préparation des prises de parole." },
      { title: "Emailing & newsletters", description: "Rédige relances et newsletters engageantes." },
    ],
    daily: [
      "Rédige posts, newsletters et messages dans le ton de la marque",
      "Prépare les visuels et programme la semaine sur chaque réseau",
      "Trie et répond aux commentaires et messages privés",
      "Suit ce qui marche et ajuste le calendrier éditorial",
    ],
    approvals: [
      "Publication d'un post",
      "Envoi d'une newsletter",
      "Réponse publique à un commentaire sensible",
      "Prise de parole auprès de la presse",
    ],
    routines: [
      { title: "Rappelle les échéances de production et de diffusion des campagnes", cadence: "Chaque jour ouvré" },
      { title: "Produit le point de la semaine sur la présence de l'entreprise", cadence: "Chaque semaine" },
      { title: "Fait la veille de la communication des concurrents", cadence: "Chaque mois" },
      { title: "Produit le bilan marketing du mois pour la direction", cadence: "Chaque mois" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "Plateforme de marque", description: "Votre promesse, votre ton et vos messages clés, sur une page que toute l'équipe peut suivre." },
      { title: "Calendrier éditorial du mois", description: "Chaque publication datée, par réseau, avec son sujet, son format et son objectif." },
      { title: "Posts et carrousels prêts à publier", description: "Textes et visuels aux couleurs de la marque, livrés pour validation avant programmation." },
      { title: "Réponses aux commentaires et messages", description: "Les réponses proposées chaque jour, et les cas sensibles signalés avant toute réponse." },
      { title: "Veille des tendances de la semaine", description: "Ce qui circule dans votre secteur et chez vos concurrents, avec les idées à reprendre." },
      { title: "Newsletter mensuelle", description: "Le sujet, le texte et la liste d'envoi, prêts à partir après votre accord." },
      { title: "Plan de campagne publicitaire", description: "Le budget, les audiences, les visuels et les indicateurs à suivre, réseau par réseau." },
      { title: "Communiqué et liste presse", description: "Le communiqué rédigé et les journalistes à contacter, avec l'angle pour chacun." },
      { title: "Rapport de performance mensuel", description: "Portée, engagement et contacts obtenus par réseau, et ce qu'il faut changer le mois suivant." },
    ],
    needs: [
      "Charte et éléments de marque",
      "Accès aux comptes des réseaux",
      "Offres et arguments à mettre en avant",
      "Calendrier de vos temps forts",
      "Photos et visuels disponibles",
    ],
    tools: [
      "Instagram",
      "Facebook",
      "LinkedIn",
      "WhatsApp",
      "Buffer",
      "Canva",
    ],
    terrain: "Elle écrit pour un public d'ici : les temps forts de l'année ivoirienne, les codes de la conversation sur WhatsApp et Facebook, et des formats assez légers pour un forfait data. Elle connaît le prix d'une campagne sur les réseaux de la place, les heures où l'audience est réveillée, et les formats qui se partagent en statut plutôt qu'en publication.",
    suggestions: [
      "Prépare les posts de la semaine",
      "Fais le rapport des réseaux du mois",
      "Propose un jeu concours",
    ],
  },
  {
    key: "koffi",
    name: "Koffi",
    pronoun: "il",
    role: "Design & Brand",
    title: "Design et marque",
    category: "Marketing et design",
    tagline: "Il habille votre marque, du logo au site.",
    pitch: "Le studio de design de la marque : identité, visuels, affiches, landing pages et vidéos. Pour une image pro et cohérente partout.",
    inAction: "Pour l'ouverture d'une boutique, Koffi produit l'affiche dans la charte, la décline en story, post et statut WhatsApp, vérifie la cohérence et livre le tout imprimable. La communication est prête en une heure.",
    skills: [
      { title: "Recherche de nom", description: "Propose des noms de marque et vérifie les domaines disponibles." },
      { title: "Charte de marque", description: "Construit l'identité visuelle, du logo aux couleurs et typographies." },
      { title: "Visuels (Canva)", description: "Produit posts, carrousels, stories et affiches brandés." },
      { title: "Maquette de page", description: "Dessine et structure la page : hiérarchie, visuels, boutons. Le texte et le référencement viennent de Fatima." },
      { title: "Site vitrine", description: "Maquette un site vitrine simple, page par page, prêt à être rédigé et mis en ligne." },
      { title: "Goodies & print", description: "Prépare les goodies et supports print-ready." },
      { title: "Contrôle qualité visuel", description: "Vérifie chaque visuel avant publication : charte et tabous." },
      { title: "Vidéo de marque", description: "Génère des contenus vidéo courts brandés." },
      { title: "Système de design", description: "Pose la bibliothèque de composants et de gabarits qui tient la marque dans la durée." },
      { title: "Fichiers prêts pour l'impression", description: "Prépare les fichiers aux formats et aux fonds perdus que l'imprimeur attend." },
    ],
    daily: [
      "Produit affiches, posts et visuels brandés à la demande",
      "Tient la cohérence visuelle sur tous les supports",
      "Décline une création en plusieurs formats (print, story, web)",
      "Vérifie chaque visuel avant publication",
    ],
    approvals: [
      "Publication d'un visuel",
      "Envoi d'un fichier à l'imprimeur",
      "Modification du logo",
      "Diffusion d'une création à un partenaire",
    ],
    routines: [
      { title: "Fait la veille de l'identité visuelle du secteur et des concurrents", cadence: "Chaque mois" },
      { title: "Signale les productions dont la livraison approche", cadence: "Chaque jour ouvré" },
      { title: "Produit le point des productions en cours", cadence: "Chaque semaine" },
      { title: "Passe en revue les supports de l'entreprise et signale ce qui a dérivé", cadence: "Chaque mois" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "Pistes de nom", description: "Des noms vérifiés, disponibles en nom de domaine, avec le sens de chacun." },
      { title: "Charte graphique", description: "Logo, couleurs, typographies et règles d'usage, sur un document partageable." },
      { title: "Affiches et flyers", description: "Prêts pour l'imprimeur, aux bons formats, avec fonds perdus." },
      { title: "Posts, carrousels et stories", description: "Aux couleurs de la marque, déclinés pour chaque réseau." },
      { title: "Déclinaisons d'un même visuel", description: "Un visuel adapté en dix formats, du print au statut WhatsApp." },
      { title: "Maquette de page", description: "La page d'accueil ou de vente dessinée, prête à être intégrée." },
      { title: "Site vitrine", description: "Quelques pages simples, à votre image, mises en ligne." },
      { title: "Goodies et signalétique", description: "T-shirts, kakémonos, enseignes : fichiers prêts pour le fournisseur." },
      { title: "Contrôle qualité visuel", description: "Chaque support relu avant diffusion : couleurs, fautes, logo, lisibilité." },
    ],
    needs: [
      "Logo et fichiers sources",
      "Charte de couleurs et polices",
      "Photos de l'entreprise",
      "Formats de sortie attendus",
      "Exemples de ce que vous aimez",
    ],
    tools: [
      "Canva",
      "Figma",
      "Google Drive",
      "Instagram",
      "Gmail",
      "Facebook",
    ],
    terrain: "Il produit pour les supports d'ici : kakemonos et bâches d'imprimeur local, affiches de point de vente, et des visuels qui restent lisibles sur un écran de téléphone d'entrée de gamme. Il compose avec les contraintes réelles, les formats que tient un imprimeur d'Abidjan et les codes qui font qu'une image circule en statut plutôt qu'en publication.",
    suggestions: [
      "Décline l’affiche pour Instagram",
      "Prépare le bon à tirer du packaging",
      "Vérifie la charte des visuels du jour",
    ],
  },
  {
    key: "kouassi",
    name: "Kouassi",
    pronoun: "il",
    role: "Commercial & Ventes",
    title: "Ventes",
    category: "Ventes et clients",
    tagline: "Il ne laisse jamais une opportunité refroidir.",
    pitch: "Le développement commercial de bout en bout : trouver les bons prospects, les relancer au bon moment, préparer les devis et garder le pipeline vivant, du premier message à la signature.",
    inAction: "Un devis envoyé il y a 5 jours reste sans réponse. Kouassi relance avec un message personnalisé, propose un appel, et prévient le commercial que le prospect a rouvert le devis deux fois. L'affaire repart.",
    skills: [
      { title: "Client idéal (ICP)", description: "Définit le profil d'entreprise à cibler en priorité à partir de votre activité." },
      { title: "Prospection B2B", description: "Trouve et qualifie des profils d'entreprises correspondant à votre cible." },
      { title: "Séquences de relance", description: "Rédige les messages d'approche J0/J3/J7 personnalisés sur WhatsApp, e-mail et LinkedIn." },
      { title: "Tri des demandes entrantes", description: "Classe les messages par intention et température, répond et pousse au rendez-vous." },
      { title: "Signaux d'achat", description: "Repère les signaux (recrutement, expansion, lancement) qui indiquent qu'un compte est prêt." },
      { title: "Scoring & suivi des leads", description: "Note chaque piste de 0 à 100 et relance, sans laisser mourir une opportunité." },
      { title: "Pricing local (FCFA)", description: "Recommande une grille de prix avec benchmark régional UEMOA, en FCFA et USD." },
      { title: "Playbook de vente", description: "Construit l'argumentaire et le pitch, pour le B2B formel comme informel." },
      { title: "Analytics des ventes", description: "Teste les messages et suit le tunnel de conversion étape par étape." },
      { title: "Négociation et remise", description: "Cadre la remise acceptable, prépare les contreparties et tient la marge." },
    ],
    daily: [
      "Qualifie les demandes entrantes (WhatsApp, e-mail, DM) et pose les bonnes questions",
      "Relance les devis en attente avec le ton juste, sans harceler",
      "Prend les rendez-vous et prépare les fiches commerciales",
      "Signale au dirigeant les affaires chaudes et celles qui coincent",
    ],
    approvals: [
      "Envoi d'un devis ou d'un prix",
      "Remise au-delà du barème",
      "Engagement de délai auprès d'un client",
      "Prise de contact avec un compte stratégique",
    ],
    routines: [
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
      { title: "Envoie le rapport d'activité de la semaine", cadence: "Chaque semaine" },
      { title: "Relance un livrable remis resté sans retour depuis trois jours", cadence: "Deux fois par semaine" },
      { title: "Revient sur une question restée sans réponse depuis 48 heures", cadence: "Chaque jour ouvré" },
      { title: "Vérifie que chacun de ses accès répond", cadence: "Chaque jour" },
    ],
    deliverables: [
      { title: "Fiche client idéal", description: "Le profil d'entreprise à viser en premier : secteur, taille, décideur, signes qui ne trompent pas." },
      { title: "Liste de 50 comptes cibles", description: "Chaque compte qualifié, avec le nom du décideur, le bon canal et la raison de l'appeler maintenant." },
      { title: "Séquence de relance J0, J3, J7", description: "Les messages prêts pour WhatsApp, e-mail et LinkedIn, personnalisés compte par compte." },
      { title: "Tri quotidien des demandes entrantes", description: "Chaque message classé chaud, tiède ou froid, avec la réponse proposée et le rendez-vous à caler." },
      { title: "Pipeline noté de 0 à 100", description: "Chaque affaire, son montant, son étape, sa note et sa prochaine action datée." },
      { title: "Grille de prix en F CFA", description: "Vos prix comparés à ceux de la région UEMOA, avec la marge tenue à chaque palier." },
      { title: "Playbook des 20 objections", description: "Les objections que vous entendez le plus, la réponse à chacune et ce qu'il vaut mieux éviter." },
      { title: "Note de négociation", description: "La remise plafond, les contreparties à demander et le point où l'on se retire." },
      { title: "Point commercial du vendredi", description: "Les affaires gagnées, perdues et bloquées de la semaine, et les trois priorités de la suivante." },
    ],
    needs: [
      "Catalogue et grille tarifaire",
      "Liste des clients et des prospects",
      "Historique des devis émis",
      "Conditions de remise autorisées",
      "Canaux par lesquels arrivent les demandes",
    ],
    tools: [
      "WhatsApp",
      "Gmail",
      "LinkedIn",
      "Google Sheets",
      "Calendly",
      "HubSpot",
    ],
    terrain: "Il vend sur les canaux d'ici : la relation se noue sur WhatsApp, le devis se règle souvent en mobile money, et un grand compte impose son propre circuit de bon de commande. Il sait à quel moment un dossier se règle en espèces, combien de relances tient un acheteur avant de se fermer, et quels circuits d'achat exigent une commande signée.",
    suggestions: [
      "Liste 50 comptes cibles à prospecter",
      "Rédige une séquence de relance",
      "Fais le point commercial de la semaine",
    ],
  },
  {
    key: "awa",
    name: "Awa",
    pronoun: "elle",
    role: "Support & Relation client",
    title: "Service client",
    category: "Ventes et clients",
    tagline: "Elle répond à vos clients, jour et nuit, sur WhatsApp.",
    pitch: "Le guichet client de l'entreprise, ouvert 24h/24, qui absorbe les demandes entrantes, y répond, et n'en laisse aucune sans suite.",
    inAction: "Un client écrit à 22h « ma livraison n'est pas arrivée ». Awa retrouve la commande, explique le statut, propose un créneau de rappel, et laisse une note pour l'équipe du matin. Le client a une réponse tout de suite ; l'équipe garde le contrôle.",
    skills: [
      { title: "Tri des tickets", description: "Classe chaque demande entrante par urgence, sentiment et sujet, et l'assigne au bon interlocuteur." },
      { title: "FAQ & articles d'aide", description: "Repère les questions récurrentes et génère les réponses et articles d'aide prêts à publier." },
      { title: "Parcours WhatsApp", description: "Conçoit les flux WhatsApp de bout en bout : accueil, KYC, paiement, FAQ, escalade." },
      { title: "Analyse de satisfaction (NPS)", description: "Analyse les retours clients, distingue promoteurs et détracteurs, remonte les verbatims." },
      { title: "Score de santé client", description: "Note chaque client selon usage, paiements et tickets pour repérer ceux à risque." },
      { title: "Suivi d'onboarding", description: "Accompagne les nouveaux clients sur leurs 30 premiers jours et détecte les décrochages." },
      { title: "Rétention / anti-churn", description: "Déclenche une séquence de sauvetage dès qu'un client montre des signes de départ." },
      { title: "Réponses types", description: "Construit la base de réponses maison et l'enrichit à chaque nouveau cas." },
      { title: "Réclamation et geste commercial", description: "Traite une réclamation, propose le geste adapté et trace ce qui a été accordé." },
      { title: "Engagement de délai", description: "Annonce un délai tenable, prévient avant qu'il passe et fait remonter ce qui coince." },
    ],
    daily: [
      "Répond aux messages clients sur Telegram et WhatsApp en quelques secondes, 24h/24",
      "Retrouve une commande, une facture ou un historique sans faire attendre",
      "Trie les demandes : ce qu'elle traite seule vs. ce qu'elle escalade",
      "Détecte les clients mécontents ou silencieux et prévient un responsable",
    ],
    approvals: [
      "Geste commercial ou remboursement",
      "Annulation d'une commande",
      "Promesse de délai faite à un client",
      "Message diffusé à toute la base client",
    ],
    routines: [
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
      { title: "Envoie le rapport d'activité de la semaine", cadence: "Chaque semaine" },
      { title: "Relance un livrable remis resté sans retour depuis trois jours", cadence: "Deux fois par semaine" },
      { title: "Revient sur une question restée sans réponse depuis 48 heures", cadence: "Chaque jour ouvré" },
      { title: "Vérifie que chacun de ses accès répond", cadence: "Chaque jour" },
    ],
    deliverables: [
      { title: "Réponses clients du jour", description: "Chaque demande reçue sur WhatsApp ou par e-mail traitée, les cas sensibles remontés." },
      { title: "Tri des demandes", description: "Chaque ticket classé par sujet et par urgence, avec le délai de réponse tenu." },
      { title: "Réponses types validées", description: "Les réponses aux vingt questions les plus fréquentes, dans le ton de votre maison." },
      { title: "Articles d'aide", description: "Des pas à pas illustrés, publiés dans votre centre d'aide ou envoyés sur WhatsApp." },
      { title: "Parcours WhatsApp", description: "Le menu d'accueil, les réponses automatiques et le passage à un humain quand il le faut." },
      { title: "Fiche de réclamation", description: "Le problème, les faits, le geste commercial proposé et le délai promis au client." },
      { title: "Alerte client à risque", description: "Les clients qui décrochent, avec la raison probable et l'action à mener cette semaine." },
      { title: "Note des causes récurrentes", description: "Ce qui revient le plus dans les plaintes, et ce qu'il faut corriger à la source." },
      { title: "Bilan de satisfaction mensuel", description: "Le score de satisfaction, son évolution et les verbatims qui l'expliquent." },
    ],
    needs: [
      "Catalogue et fiches produits",
      "Historique des commandes",
      "Politique de retour et de remboursement",
      "Questions fréquentes déjà traitées",
      "Règles d'escalade",
    ],
    tools: [
      "Telegram",
      "WhatsApp",
      "Gmail",
      "Google Sheets",
      "Notion",
      "Zendesk",
    ],
    terrain: "Elle répond là où les clients écrivent, retrouve un règlement mobile money à partir d'un simple numéro de transaction, et comprend le français d'ici comme les tournures du quotidien. Elle connaît les heures où le réseau sature, ce qu'un client accepte d'attendre, et la différence entre un incident d'opérateur et une panne de votre service.",
    suggestions: [
      "Réponds aux messages clients du jour",
      "Rédige les réponses types de la FAQ",
      "Fais le bilan de satisfaction du mois",
    ],
  },
  {
    key: "adjoua",
    name: "Adjoua",
    pronoun: "elle",
    role: "Recrutement",
    title: "Recrutement",
    category: "RH",
    tagline: "Elle trouve et évalue les bons profils.",
    pitch: "Le recrutement de bout en bout : de la fiche de poste au sourcing, à l'évaluation et à la lettre d'offre. Pour embaucher juste et vite.",
    inAction: "Pour un poste de comptable, Adjoua rédige la fiche, source 15 profils, en présélectionne 5 notés, prépare le guide d'entretien et programme les rendez-vous. Le dirigeant n'a plus qu'à rencontrer les meilleurs.",
    skills: [
      { title: "Fiche de poste", description: "Rédige des fiches de poste claires et attractives." },
      { title: "Sourcing candidats", description: "Trouve des profils sur LinkedIn, ciblés par poste et localisation." },
      { title: "Matching CV ↔ offre", description: "Note l'adéquation d'un CV ou profil LinkedIn à vos offres." },
      { title: "Messages d'approche", description: "Rédige les messages d'approche et e-mails de recrutement personnalisés." },
      { title: "Guide d'entretien & scoring", description: "Prépare l'entretien structuré et la grille de notation du candidat." },
      { title: "Business case candidat", description: "Génère un exercice de mise en situation et le corrige." },
      { title: "Vérification de références", description: "Structure et mène la prise de références." },
      { title: "Suivi du pipeline (ATS)", description: "Suit chaque candidat étape par étape, relances et échéances." },
      { title: "Lettre d'offre", description: "Rédige la lettre d'offre conforme OHADA, et passe la main à Ibrahim pour le contrat de travail." },
      { title: "Benchmark rémunération", description: "Compare salaire et avantages au marché." },
    ],
    daily: [
      "Rédige les fiches de poste et diffuse les offres",
      "Source et présélectionne les candidats",
      "Prépare les entretiens et les grilles de notation",
      "Suit chaque candidat dans le pipeline, relances comprises",
    ],
    approvals: [
      "Publication d'une offre",
      "Envoi d'un message à un candidat",
      "Convocation à un entretien",
      "Envoi d'une lettre d'offre",
    ],
    routines: [
      { title: "Fait le point sur le marché de l'emploi pour les postes ouverts", cadence: "Chaque semaine" },
      { title: "Produit le point hebdomadaire du recrutement", cadence: "Chaque semaine" },
      { title: "Repère les candidats et évaluateurs qui attendent, et prépare les messages", cadence: "Chaque jour" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
      { title: "Envoie le rapport d'activité de la semaine", cadence: "Chaque semaine" },
    ],
    deliverables: [
      { title: "Fiche de poste prête à publier", description: "Missions, profil, conditions et critères de sélection, dans le ton de votre maison." },
      { title: "Longue liste de 30 profils", description: "Des candidats sourcés sur LinkedIn et les jobboards d'ici, avec la raison de chaque choix." },
      { title: "Liste courte notée", description: "Les cinq meilleurs CV comparés à l'offre, critère par critère, avec leurs points à creuser." },
      { title: "Messages d'approche", description: "Les premiers messages aux candidats, personnalisés, prêts pour WhatsApp, e-mail ou LinkedIn." },
      { title: "Guide d'entretien et grille notée", description: "Les questions par compétence et une grille qui permet de comparer les candidats." },
      { title: "Compte rendu de prise de références", description: "Ce que disent les anciens employeurs, question par question." },
      { title: "Benchmark de rémunération", description: "Le salaire du marché pour ce poste à Abidjan, par niveau d'expérience." },
      { title: "Lettre d'offre", description: "L'offre au candidat retenu, avec salaire, date de prise de poste et conditions." },
      { title: "Suivi du pipeline de recrutement", description: "Chaque candidat, son étape, la prochaine action et le délai tenu." },
    ],
    needs: [
      "Organigramme et postes ouverts",
      "Fourchettes de rémunération",
      "Critères de sélection",
      "Comptes de diffusion des offres",
      "Disponibilités des évaluateurs",
    ],
    tools: [
      "LinkedIn",
      "Gmail",
      "Google Sheets",
      "Calendly",
      "Notion",
      "Zoom",
    ],
    terrain: "Elle source sur les canaux d'ici, de l'Agence Emploi Jeunes aux groupes métier sur WhatsApp et aux écoles d'Abidjan, et connaît les pièces exigées au moment de l'embauche. Elle sait ce qu'un poste se paie réellement selon l'expérience, et elle prépare un dossier complet, de la déclaration CNPS au contrat conforme au droit ivoirien.",
    suggestions: [
      "Rédige une fiche de poste",
      "Trie les CV reçus pour cette offre",
      "Prépare un guide d’entretien noté",
    ],
  },
  {
    key: "mamadou",
    name: "Mamadou",
    pronoun: "il",
    role: "Finance & Comptabilité",
    title: "Finance",
    category: "Finance et investissement",
    tagline: "Il garde vos comptes clairs et vos dossiers bancables.",
    pitch: "Le pilotage financier de l'entreprise : comptabilité OHADA, contrôle de gestion, business plan et prévisionnel. De quoi décider sur des chiffres justes et obtenir des financements.",
    inAction: "Avant un rendez-vous bancaire, Mamadou reconstitue le prévisionnel à 3 ans, prépare le plan de remboursement, repère les points faibles du dossier et livre un PDF propre. Le dirigeant arrive préparé.",
    skills: [
      { title: "Comptabilité OHADA", description: "Structure la comptabilité de l'entreprise selon le référentiel OHADA." },
      { title: "Audit & contrôle de gestion", description: "Audit comptable et contrôle de gestion pour garder les comptes carrés." },
      { title: "Business plan", description: "Construit le business plan (acquisition + revenus) pour un prêt bancaire ou une subvention." },
      { title: "Modélisation financière", description: "Bâtit le prévisionnel et les projections à 3 ans." },
      { title: "Dimensionnement de marché", description: "Chiffre la taille du marché visé, pour étayer un business plan devant une banque ou un bailleur." },
      { title: "Veille des prix", description: "Suit les prix pratiqués dans votre secteur, pour situer vos marges." },
      { title: "Clôture mensuelle", description: "Boucle le mois, rapprochements faits et écritures passées, avant le 10." },
      { title: "Trésorerie à 13 semaines", description: "Projette la trésorerie semaine par semaine et signale le point bas à l'avance." },
      { title: "Rapprochement bancaire", description: "Rapproche relevés bancaires, mobile money et caisse, et isole les suspens." },
      { title: "Calendrier fiscal et social", description: "Tient les échéances DGI et CNPS de l'année et prévient avant chacune." },
    ],
    daily: [
      "Structure et tient la comptabilité selon le référentiel OHADA",
      "Prépare les tableaux de trésorerie et de marge",
      "Émet les factures, suit les relances clients et monte les dossiers de financement",
      "Alerte le dirigeant dès qu'un chiffre sort des clous",
    ],
    approvals: [
      "Transmission d'une liasse à un tiers",
      "Dépôt d'une déclaration",
      "Envoi d'un dossier à une banque",
      "Écriture de régularisation",
    ],
    routines: [
      { title: "Rappelle les échéances fiscales et sociales", cadence: "Chaque jour ouvré" },
      { title: "Produit le point de trésorerie avant les décaissements de la semaine", cadence: "Chaque semaine" },
      { title: "Ouvre la clôture du mois et prépare la liasse", cadence: "Chaque mois" },
      { title: "Prépare les relances clients à partir de la balance âgée", cadence: "Chaque semaine" },
      { title: "Produit le suivi budgétaire du mois", cadence: "Chaque mois" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "Saisie et balance SYSCOHADA", description: "Vos pièces saisies, la balance et le grand livre à jour chaque mois." },
      { title: "Rapprochement bancaire", description: "Chaque ligne de relevé pointée, et les écarts expliqués." },
      { title: "Clôture mensuelle", description: "Le compte de résultat du mois et la note d'écart avec le budget." },
      { title: "Trésorerie à 13 semaines", description: "Encaissements et décaissements prévus, semaine par semaine, avec les alertes." },
      { title: "Devis, factures et relances", description: "Émis dans les délais, et les impayés relancés avec le bon ton." },
      { title: "Calendrier fiscal et social", description: "Les déclarations DGI et CNPS du mois, préparées avant l'échéance." },
      { title: "Budget et suivi budgétaire", description: "Le budget de l'année et l'écart constaté chaque mois, poste par poste." },
      { title: "Prévisionnel à trois ans", description: "Compte de résultat, trésorerie et hypothèses, prêts pour un banquier." },
      { title: "Dossier pour la banque", description: "États financiers, prévisionnel et note de présentation pour un crédit." },
    ],
    needs: [
      "Relevés bancaires et journaux",
      "Factures d'achat et de vente",
      "Grille des salaires",
      "Échéancier fiscal et social",
      "Historique des financements obtenus",
    ],
    tools: [
      "Google Sheets",
      "Excel",
      "Sage",
      "QuickBooks",
      "Gmail",
      "Banques",
    ],
    terrain: "Il tient les comptes au référentiel SYSCOHADA révisé, connaît les échéances de la DGI, les taux de cotisation CNPS et ce qu'une banque de la zone UEMOA attend dans un dossier. Il connaît le calendrier fiscal de l'année, les pièces qu'un commissaire aux comptes réclame, et la façon dont une banque de la place lit un bilan avant d'accorder une ligne.",
    suggestions: [
      "Fais le rapprochement bancaire du mois",
      "Prépare la trésorerie à 13 semaines",
      "Relance les factures impayées",
      "Prépare le dossier pour la banque",
    ],
  },
  {
    key: "salif",
    name: "Salif",
    pronoun: "il",
    role: "Opérations & Logistique",
    title: "Opérations",
    category: "Finance et investissement",
    tagline: "Il fait tourner les stocks, les achats et les livraisons du quotidien.",
    pitch: "Le moteur logistique : achats et fournisseurs, réception et contrôle des marchandises, stocks et seuils d'alerte, livraisons. Pour que rien ne manque et que rien ne dorme en réserve.",
    inAction: "Lundi matin, Salif signale deux références passées sous le seuil, consulte trois fournisseurs, prépare les bons de commande et vérifie que la livraison de vendredi a bien quitté le port. Le dirigeant voit tout d'un coup d'œil.",
    skills: [
      { title: "Tournée de livraison", description: "Organise les tournées et calcule le coût au kilomètre." },
      { title: "Rupture et invendu", description: "Repère ce qui va manquer et ce qui dort en réserve, et dit quoi faire." },
      { title: "Suivi de stock", description: "Surveille les stocks, alerte avant la rupture et calcule le réassort." },
      { title: "Approvisionnements", description: "Suit les sources d'approvisionnement et les commandes fournisseurs." },
      { title: "Point d'exploitation", description: "Fait chaque semaine le point sur les commandes, les stocks et les tâches en retard." },
      { title: "Suivi des tâches", description: "Suit les tâches d'exploitation, relance ce qui traîne et rend le point au dirigeant (Notion + e-mail)." },
      { title: "Suivi fournisseurs", description: "Tient la liste des fournisseurs, les commandes en cours et les échéances de règlement." },
      { title: "Import et douane", description: "Suit un dossier d'import du connaissement à la sortie de marchandise." },
      { title: "Réception et contrôle", description: "Contrôle les livraisons à l'arrivée et documente les écarts avec le fournisseur." },
      { title: "Inventaire tournant", description: "Organise les comptages par zone pour garder un stock juste sans tout arrêter." },
    ],
    daily: [
      "Consulte les fournisseurs et les compare à conditions égales",
      "Surveille les stocks et alerte avant la rupture",
      "Contrôle les réceptions et signale les écarts de livraison",
      "Produit les indicateurs clés de la semaine",
    ],
    approvals: [
      "Changement de fournisseur",
      "Dérogation sur un seuil d'alerte",
      "Commande passée à un fournisseur",
      "Blocage d'une livraison",
    ],
    routines: [
      { title: "Signale les références qui vont manquer, avant la rupture", cadence: "Chaque jour ouvré" },
      { title: "Sort les opérations d'entretien de la semaine et les retards", cadence: "Chaque semaine" },
      { title: "Sort le stock qui dort et ce qui va périmer", cadence: "Chaque mois" },
      { title: "Contrôle les réceptions du jour, tant qu'une réserve est possible", cadence: "Chaque jour" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "État de stock avec seuils", description: "Le stock de chaque article, ses seuils d'alerte et les commandes à passer." },
      { title: "Alerte rupture et invendus", description: "Les articles qui vont manquer et ceux qui dorment, avec l'action proposée." },
      { title: "Comparatif de trois fournisseurs", description: "Prix, délais, conditions et fiabilité, pour choisir sur des faits." },
      { title: "Bons de commande", description: "Préparés à partir des seuils, prêts à envoyer après votre accord." },
      { title: "Plan de tournée de livraison", description: "L'ordre des livraisons, le coût de la tournée et le coût par livraison." },
      { title: "Fiche de réception", description: "Ce qui est arrivé, ce qui manque et les réserves à faire au fournisseur." },
      { title: "Suivi import et douane", description: "Les étapes de chaque commande importée, les pièces et les frais à prévoir." },
      { title: "Inventaire tournant", description: "Le planning des comptages et l'analyse des écarts trouvés." },
      { title: "Point d'exploitation hebdomadaire", description: "Stocks, livraisons, fournisseurs et incidents de la semaine, sur une page." },
    ],
    needs: [
      "Conditions d'achat et délais fournisseurs",
      "État des stocks",
      "Liste des fournisseurs",
      "Modèles de bon de commande",
      "Seuils d'alerte convenus",
    ],
    tools: [
      "Google Sheets",
      "Notion",
      "WhatsApp",
      "QuickBooks",
      "Odoo",
      "Gmail",
    ],
    terrain: "Il règle ses fournisseurs en mobile money comme en virement, tient les formalités de douane et d'import, et anticipe les ruptures liées aux délais de dédouanement. Il connaît les délais réels entre le port et l'entrepôt, ce qu'un fournisseur accepte comme retard de règlement, et les pièces qui bloquent une sortie de marchandise.",
    suggestions: [
      "Fais l’état des stocks de la semaine",
      "Compare trois devis de fournisseurs",
      "Prépare la tournée de livraison",
    ],
  },
  {
    key: "alioune",
    name: "Alioune",
    pronoun: "il",
    role: "Investissement",
    title: "Investissement",
    category: "Finance et investissement",
    tagline: "Il instruit vos dossiers d'investissement, du sourcing au suivi de participation.",
    pitch: "L'instruction des investissements de bout en bout : sourcing contre la thèse du fonds, lecture de la salle de données, audit du modèle, note au comité, valorisation et suivi de la participation.",
    inAction: "Un dossier Série A arrive pour le comité de vendredi. Alioune vérifie la thèse du fonds, inventorie la data room, repère deux chiffres de revenus qui se contredisent, prépare les questions au fondateur et livre la note de comité avec les scénarios de valorisation.",
    skills: [
      { title: "Tri des dossiers entrants", description: "Note chaque dossier reçu contre la thèse d'investissement du fonds et priorise l'attention du comité." },
      { title: "Lecture de data room", description: "Inventorie les pièces d'une salle de données et signale ce qui manque ou se contredit." },
      { title: "Due diligence", description: "Mène la diligence commerciale, juridique et opérationnelle avant investissement." },
      { title: "Audit du modèle financier", description: "Vérifie les hypothèses et la cohérence du modèle financier transmis par le fondateur." },
      { title: "Note de comité", description: "Rédige la note de comité avec les écarts constatés, les scénarios et les points bloquants." },
      { title: "Valorisation & term sheet", description: "Prépare la valorisation et les termes clés de l'offre à négocier." },
      { title: "KYC / AML", description: "Réalise les vérifications d'identité et de conformité anti-blanchiment sur les parties prenantes." },
      { title: "Comparables", description: "Recherche les transactions et valorisations comparables sur le secteur visé." },
      { title: "Suivi de participation", description: "Suit la performance, la trésorerie et les alertes convenues après investissement." },
      { title: "Reporting souscripteurs", description: "Prépare le reporting périodique destiné aux souscripteurs du fonds." },
    ],
    daily: [
      "Note les dossiers contre la thèse réelle du fonds",
      "Inventorie les pièces et signale les manques et incohérences",
      "Audite les modèles financiers et prépare les questions à la direction",
      "Suit les participations, la trésorerie et les alertes convenues",
    ],
    approvals: [
      "Transmission d'un prix ou d'une offre",
      "Contact d'un dirigeant ou co-investisseur",
      "Diffusion d'une note de comité hors du fonds",
      "Rejet définitif d'un dossier",
    ],
    routines: [
      { title: "Fait la veille des secteurs et des pays couverts par la thèse du fonds", cadence: "Chaque semaine" },
      { title: "Produit le point hebdomadaire du pipeline", cadence: "Chaque semaine" },
      { title: "Surveille les participations et déclenche les alertes convenues", cadence: "Chaque jour ouvré" },
      { title: "Repère les dossiers bloqués et prépare les relances", cadence: "Chaque semaine" },
      { title: "Prépare la séance de comité", cadence: "Chaque semaine" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "Tri des dossiers entrants", description: "Chaque dossier noté sur votre thèse, avec la décision proposée : creuser ou décliner." },
      { title: "Inventaire de salle de données", description: "Les pièces reçues, celles qui manquent et les questions qu'elles soulèvent." },
      { title: "Liste de questions à la direction", description: "Les points à éclaircir avant le comité, classés par importance." },
      { title: "Audit du modèle financier", description: "Les hypothèses vérifiées une à une, les erreurs de formule et les scénarios à tester." },
      { title: "Note de vérification préalable", description: "Juridique, financier, commercial : ce qui est confirmé et ce qui reste un risque." },
      { title: "Tableau de comparables", description: "Les sociétés et opérations proches, avec leurs multiples de valorisation." },
      { title: "Note de comité d'investissement", description: "La thèse, les risques, la valorisation proposée et la recommandation." },
      { title: "Contrôle KYC et anti-blanchiment", description: "Les dirigeants et actionnaires vérifiés, avec les points d'alerte relevés." },
      { title: "Reporting trimestriel aux souscripteurs", description: "La vie de chaque participation, ses chiffres clés et les alertes à suivre." },
    ],
    needs: [
      "Thèse et critères du fonds",
      "Accès aux salles de données",
      "Historique des dossiers instruits",
      "Modèle de note de comité",
      "Calendrier du comité d'investissement",
    ],
    tools: [
      "Google Drive",
      "Excel",
      "DocuSign",
      "Gmail",
      "Slack",
      "Notion",
    ],
    terrain: "Il instruit dans le cadre de la région : droit OHADA, réglementation BCEAO pour les acteurs financiers, formalités du CEPICI et comparables des transactions de la zone UEMOA. Il sait ce qu'un fonds d'ici attend dans une data room, des états certifiés au registre du commerce, et ce qui retarde une opération au moment de la signature.",
    suggestions: [
      "Trie les nouveaux dossiers reçus",
      "Audite ce modèle financier",
      "Fais le tableau des comparables",
      "Prépare la note de comité",
    ],
  },
  {
    key: "nadia",
    name: "Nadia",
    pronoun: "elle",
    role: "Data & Analytics",
    title: "Données",
    category: "Données",
    tagline: "Elle transforme vos chiffres en décisions.",
    pitch: "L'intelligence des données de l'entreprise : tableaux de bord, rapports, prévisions et scoring. De quoi piloter sur du concret plutôt qu'au feeling.",
    inAction: "Chaque lundi, Nadia envoie le tableau de bord de la semaine, met en avant les 3 alertes qui comptent et prévoit la trésorerie à 30 jours. Le comité de direction démarre sur des faits.",
    skills: [
      { title: "Tableaux de bord", description: "Transforme vos Google Sheets en tableaux de bord clairs et partageables." },
      { title: "Rapports KPI", description: "Produit les rapports hebdo, mensuels et trimestriels automatiquement." },
      { title: "Prévision de la demande", description: "Prévoit la demande par produit pour ajuster les commandes." },
      { title: "Prévision de trésorerie", description: "Projette les besoins de cash à J+7 / J+14 / J+30." },
      { title: "Scoring de performance", description: "Note et classe vos points de vente ou distributeurs (haut / moyen / faible)." },
      { title: "Synthèse de réunions", description: "Analyse les comptes-rendus et en extrait décisions et tâches." },
      { title: "Qualité de la donnée", description: "Repère doublons, trous et valeurs aberrantes avant de publier un chiffre." },
      { title: "Segmentation et cohortes", description: "Découpe vos clients par cohorte pour voir qui revient et qui décroche." },
      { title: "Questionnaire et dépouillement", description: "Construit le questionnaire, collecte les réponses et rend le dépouillement." },
      { title: "Réel contre budget", description: "Compare le réalisé au budget, poste par poste, et explique les écarts." },
    ],
    daily: [
      "Met à jour les tableaux de bord depuis vos fichiers",
      "Produit les rapports hebdo et mensuels automatiquement",
      "Signale les écarts et les points de vente qui décrochent",
      "Prépare des synthèses de réunion actionnables",
    ],
    approvals: [
      "Diffusion d'un tableau de bord hors de l'entreprise",
      "Partage d'une donnée client",
      "Publication d'un chiffre",
      "Alerte envoyée à toute l'équipe",
    ],
    routines: [
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
      { title: "Envoie le rapport d'activité de la semaine", cadence: "Chaque semaine" },
      { title: "Relance un livrable remis resté sans retour depuis trois jours", cadence: "Deux fois par semaine" },
      { title: "Revient sur une question restée sans réponse depuis 48 heures", cadence: "Chaque jour ouvré" },
      { title: "Vérifie que chacun de ses accès répond", cadence: "Chaque jour" },
    ],
    deliverables: [
      { title: "Tableau de bord partageable", description: "Vos indicateurs clés à jour, lisibles sur téléphone par toute la direction." },
      { title: "Rapport hebdomadaire", description: "Ce qui a bougé cette semaine, pourquoi, et ce qu'il faut surveiller." },
      { title: "Rapport mensuel de direction", description: "Les chiffres du mois comparés au budget et au mois précédent." },
      { title: "Prévision de la demande", description: "Les ventes attendues par produit et par point de vente, pour commander juste." },
      { title: "Prévision de trésorerie", description: "L'argent disponible dans les semaines à venir, selon plusieurs scénarios." },
      { title: "Classement des points de vente", description: "Chaque site noté sur sa performance, avec les écarts à expliquer." },
      { title: "Segmentation des clients", description: "Vos clients regroupés par comportement, et ce que chaque groupe rapporte." },
      { title: "Rapport de qualité des données", description: "Les doublons, trous et incohérences trouvés, et comment les corriger." },
      { title: "Enquête et dépouillement", description: "Le questionnaire, la collecte et l'analyse des réponses." },
    ],
    needs: [
      "Fichiers de ventes et de stocks",
      "Liste des points de vente",
      "Objectifs et budget de l'année",
      "Relevés de paiement",
      "Comptes rendus de réunion",
    ],
    tools: [
      "Google Sheets",
      "Looker",
      "Notion",
      "Fireflies",
      "Gmail",
      "Excel",
    ],
    terrain: "Elle lit les données telles qu'elles arrivent ici : relevés mobile money, ventes par point de vente, saisonnalité des campagnes agricoles et des grandes fêtes. Elle sait ce qu'un relevé d'opérateur contient vraiment, comment recoller des ventes saisies à la main, et quels écarts viennent d'un jour férié plutôt que d'une baisse d'activité.",
    suggestions: [
      "Sors les ventes de la semaine par région",
      "Prépare le rapport mensuel de direction",
      "Prévois la demande du mois prochain",
      "Vérifie la qualité de nos données",
    ],
  },
  {
    key: "ibrahim",
    name: "Ibrahim",
    pronoun: "il",
    role: "Juridique & Conformité",
    title: "Juridique",
    category: "Juridique",
    tagline: "Il tient le juridique carré, pour le privé comme pour le public.",
    pitch: "Le réflexe juridique du quotidien : contrats OHADA, revue de documents, conformité et veille réglementaire. De quoi agir vite sans se mettre en risque.",
    inAction: "Un partenaire envoie un contrat à signer. Ibrahim le relit, pointe deux clauses à risque, propose une reformulation, et attend la validation du dirigeant avant tout retour. Rien ne s'engage sans accord humain.",
    skills: [
      { title: "Contrats commerciaux OHADA", description: "Rédige les contrats commerciaux conformes OHADA." },
      { title: "Contrats de travail", description: "Génère les contrats de travail (OHADA + droit local)." },
      { title: "Revue juridique", description: "Relit les documents entrants et signale les risques." },
      { title: "Veille contractuelle", description: "Surveille les échéances et clauses de vos contrats." },
      { title: "Conformité des données (DCP)", description: "Met en conformité la protection des données personnelles." },
      { title: "Risques réglementaires", description: "Cartographie les risques réglementaires par activité et par pays." },
      { title: "Veille réglementaire", description: "Suit la réglementation (fintech UEMOA et secteurs régulés)." },
      { title: "Création de société", description: "Accompagne l'incorporation en Côte d'Ivoire et à l'international." },
      { title: "Recouvrement amiable", description: "Rédige la relance, puis la mise en demeure, avant que le dossier parte au contentieux." },
      { title: "Marque et signes distinctifs", description: "Prépare le dépôt de marque et surveille les usages qui empiètent sur la vôtre." },
    ],
    daily: [
      "Rédige et relit les contrats commerciaux et de travail",
      "Signale les risques dans un document entrant",
      "Suit les échéances contractuelles et réglementaires",
      "Prépare les pièces pour l'administration",
    ],
    approvals: [
      "Envoi d'un contrat à un tiers",
      "Signature ou paraphe",
      "Dépôt d'une pièce auprès d'une administration",
      "Position juridique communiquée à l'extérieur",
    ],
    routines: [
      { title: "Fait le point des échéances juridiques des quatre semaines à venir", cadence: "Chaque semaine" },
      { title: "Suit les créances en recouvrement", cadence: "Deux fois par semaine" },
      { title: "Signale ce qui change dans la réglementation qui touche l'entreprise", cadence: "Chaque semaine" },
      { title: "Relit le portefeuille de contrats et signale ce qui a dérivé", cadence: "Chaque mois" },
      { title: "Envoie le point de fin de journée", cadence: "Chaque jour ouvré" },
    ],
    deliverables: [
      { title: "Contrat commercial OHADA", description: "Rédigé ou relu, avec les clauses qui vous protègent et celles à négocier." },
      { title: "Note de risque sur un document reçu", description: "Chaque clause dangereuse relevée, avec la modification à demander." },
      { title: "Tableau des échéances", description: "Renouvellements, préavis et dates limites de tous vos contrats, relancés à temps." },
      { title: "Dossier de création de société", description: "Statuts, pièces et étapes au guichet du CEPICI, dans l'ordre." },
      { title: "Registre de conformité des données", description: "Les données personnelles que vous traitez et les démarches auprès de l'ARTCI." },
      { title: "Veille réglementaire", description: "Les textes nouveaux qui touchent votre secteur, et ce qu'ils vous imposent." },
      { title: "Mise en demeure", description: "Le dossier de créance et la lettre prête, avant tout recours judiciaire." },
      { title: "Dossier de dépôt de marque", description: "La recherche d'antériorité et le dépôt auprès de l'OAPI." },
      { title: "Procès-verbal d'assemblée", description: "Le projet de PV et le calendrier de vos obligations de société." },
    ],
    needs: [
      "Statuts et registre de la société",
      "Contrats en cours",
      "Modèles déjà utilisés dans l'entreprise",
      "Liste des échéances contractuelles",
      "Pays où vous opérez",
    ],
    tools: [
      "DocuSign",
      "Google Drive",
      "Gmail",
      "Notion",
      "Google Sheets",
      "Excel",
    ],
    terrain: "Il travaille sur le droit qui s'applique ici : actes uniformes OHADA, code du travail ivoirien, formalités du CEPICI et protection des données personnelles sous l'autorité de l'ARTCI. Il sait ce qu'un greffe exige pour une modification statutaire, ce qu'une clause vaut devant un juge ivoirien, et les délais réels d'une formalité au registre du commerce.",
    suggestions: [
      "Relis ce contrat et signale les risques",
      "Rédige une mise en demeure",
      "Liste les échéances de nos contrats",
      "Prépare le dépôt de notre marque",
    ],
  },
];

export const EXPERT_KEYS = EXPERTS.map((e) => e.key);

export function getExpert(key: string): Expert | undefined {
  return EXPERTS.find((e) => e.key === key);
}

export const EXPERT_CATEGORIES: string[] = [
  "Direction",
  "Marketing et design",
  "Ventes et clients",
  "RH",
  "Finance et investissement",
  "Données",
  "Juridique",
];
